version: '3.3'
services:
  postgres-customer:
    image: "postgres:10"
  postgres-order:
    image: "postgres:10"

  customer-server:
    build:
      context: customer
      dockerfile: Dockerfile
    image: zhenik/inmt-customer:${TAG}
    ports:
      - 9082:8080
    depends_on:
      - postgres-customer

  order-server:
    build:
      context: order
      dockerfile: Dockerfile
    image: zhenik/inmt-order:${TAG}
    ports:
      - 9081:8080
    depends_on:
      - postgres-order
      - customer-server
